<?
$PERM["personal"]["G2"]="R";
$PERM["personal"]["*"]="R";
$PERM["catalog"]["2"]="R";
$PERM["catalog"]["5"]="X";
$PERM["documents"]["5"]="X";
$PERM["stati"]["2"]="R";
$PERM["stati"]["5"]="X";
$PERM["go-i-chs"]["2"]="R";
$PERM["docs"]["5"]="X";
$PERM["img"]["2"]="X";
$PERM["/"]["2"]="R";
?>